const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.primary-nav');
if(menu){menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.style.display=open?'none':'flex';if(!open){Object.assign(nav.style,{position:'absolute',top:'70px',left:'17px',right:'17px',flexDirection:'column',alignItems:'stretch',padding:'18px',gap:'4px',background:'#111418',border:'1px solid #2a2f36'});}})}

const dropdownCss=`.nav-dropdown{position:relative;display:flex;align-items:center;height:100%}.nav-drop-trigger{appearance:none;border:0;background:transparent;color:inherit;font:inherit;font-size:12px;font-weight:600;display:flex;align-items:center;gap:6px;padding:12px 0;cursor:pointer}.nav-drop-trigger span{font-size:14px;line-height:1;transition:transform .2s ease}.nav-dropdown-menu{position:absolute;top:calc(100% + 14px);left:50%;width:470px;transform:translate(-50%,-8px);padding:20px;background:#f4f0e8;color:#171716;border:1px solid rgba(20,20,18,.12);border-radius:16px;box-shadow:0 22px 55px rgba(0,0,0,.26);display:grid;grid-template-columns:1fr 1fr;gap:20px;opacity:0;visibility:hidden;pointer-events:none;transition:opacity .2s ease,transform .2s ease,visibility .2s ease;z-index:80}.nav-dropdown:hover .nav-dropdown-menu,.nav-dropdown:focus-within .nav-dropdown-menu,.nav-dropdown.is-open .nav-dropdown-menu{opacity:1;visibility:visible;pointer-events:auto;transform:translate(-50%,0)}.nav-dropdown:hover .nav-drop-trigger span,.nav-dropdown.is-open .nav-drop-trigger span{transform:rotate(180deg)}.nav-menu-group{display:flex;flex-direction:column;gap:2px}.nav-menu-label{font-size:9px;letter-spacing:.14em;font-weight:800;color:#8b8273;margin:0 0 8px;padding:0 8px}.nav-menu-group a{font-size:13px;color:#5c5a55;padding:8px;border-radius:8px;line-height:1.25;transition:background .18s ease,color .18s ease,transform .18s ease}.nav-menu-group a:hover{background:#e7e0d4;color:#111;transform:translateX(2px)}.nav-menu-cta{grid-column:1/-1;display:flex;align-items:center;justify-content:space-between;gap:16px;margin-top:2px;padding:14px 15px;background:#171716;color:#f4f0e8;border-radius:11px}.nav-menu-cta strong{display:block;font-size:12px;font-weight:700;margin-bottom:3px}.nav-menu-cta small{display:block;color:#aaa59b;font-size:10px}.nav-menu-cta b{font-size:18px;font-weight:400}.nav-industries-menu{width:400px;grid-template-columns:1fr 1fr}@media(max-width:1000px){.nav-dropdown{display:block;height:auto;width:100%}.nav-drop-trigger{width:100%;justify-content:space-between;padding:10px 0}.nav-dropdown-menu{position:static;width:100%;transform:none!important;display:none;opacity:1;visibility:visible;pointer-events:auto;box-shadow:none;border-radius:10px;padding:12px;margin:0 0 8px;background:#171a1d;color:#f4f0e8;grid-template-columns:1fr}.nav-dropdown.is-open .nav-dropdown-menu{display:grid}.nav-menu-label{color:#8d918f}.nav-menu-group a{color:#d7d9d6}.nav-menu-group a:hover{background:#22272b;color:#fff}.nav-menu-cta{background:#24292d}.nav-menu-cta small{color:#aeb2b0}}@media(prefers-reduced-motion:reduce){.nav-dropdown-menu,.nav-drop-trigger span,.nav-menu-group a{transition:none}}`;
const style=document.createElement('style');style.textContent=dropdownCss;document.head.appendChild(style);

function buildDropdown(label,groups,ctaText,ctaSub,ctaHref,extraClass=''){
 const wrap=document.createElement('div');wrap.className='nav-dropdown';
 const trigger=document.createElement('button');trigger.className='nav-drop-trigger';trigger.type='button';trigger.setAttribute('aria-expanded','false');trigger.innerHTML=`${label} <span>⌄</span>`;
 const panel=document.createElement('div');panel.className=`nav-dropdown-menu ${extraClass}`;
 groups.forEach(group=>{const g=document.createElement('div');g.className='nav-menu-group';const title=document.createElement('span');title.className='nav-menu-label';title.textContent=group.title;g.appendChild(title);group.links.forEach(item=>{const a=document.createElement('a');a.href=item[1];a.textContent=item[0];g.appendChild(a)});panel.appendChild(g)});
 const cta=document.createElement('a');cta.className='nav-menu-cta';cta.href=ctaHref;cta.innerHTML=`<span><strong>${ctaText}</strong><small>${ctaSub}</small></span><b>↗</b>`;panel.appendChild(cta);wrap.append(trigger,panel);return wrap;
}

if(nav){
 const services=[...nav.children].find(a=>a.tagName==='A'&&a.textContent.trim().toLowerCase()==='services');
 const industries=[...nav.children].find(a=>a.tagName==='A'&&a.textContent.trim().toLowerCase()==='industries');
 if(services)services.replaceWith(buildDropdown('Services',[{title:'DIGITAL EXPERIENCE',links:[['Web Design & Development','web-design.html'],['Website Redesign','web-design.html#redesign'],['E-commerce','web-design.html#ecommerce'],['Mobile Applications','mobile-products.html']]},{title:'GROWTH & VISIBILITY',links:[['SEO & Search','seo-search.html'],['Local SEO & Business Profiles','seo-search.html#local'],['Digital Growth & CRO','digital-growth.html']]},{title:'SOFTWARE & AI',links:[['Custom Software & Platforms','software-platforms.html'],['AI & Automation','ai-automation.html'],['Mobile Products','mobile-products.html']]}],'Not sure what you need?','Tell us what you are trying to improve.','contact.html'));
 if(industries)industries.replaceWith(buildDropdown('Industries',[{title:'WHO WE WORK WITH',links:[['Trades & Home Services','industries.html#trades'],['Professional Services','industries.html#professional'],['Health & Beauty','industries.html#health']]},{title:'SECTORS',links:[['Hospitality & Food','industries.html#hospitality'],['Retail & E-commerce','industries.html#retail'],['Property','industries.html#property']]}],'Explore all industries','See where we can help your business.','industries.html','nav-industries-menu'));
}

document.querySelectorAll('.nav-drop-trigger').forEach(button=>button.addEventListener('click',()=>{const parent=button.closest('.nav-dropdown');const open=parent.classList.toggle('is-open');button.setAttribute('aria-expanded',String(open));document.querySelectorAll('.nav-dropdown').forEach(other=>{if(other!==parent){other.classList.remove('is-open');const trigger=other.querySelector('.nav-drop-trigger');if(trigger)trigger.setAttribute('aria-expanded','false')}})}));
document.addEventListener('click',e=>{if(!e.target.closest('.nav-dropdown'))document.querySelectorAll('.nav-dropdown').forEach(d=>{d.classList.remove('is-open');const t=d.querySelector('.nav-drop-trigger');if(t)t.setAttribute('aria-expanded','false')})});
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{if(innerWidth<=1000&&nav)nav.style.display='none'}));
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();