const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.primary-nav');
if(menu&&nav){menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.style.display=open?'none':'flex';if(!open)Object.assign(nav.style,{position:'absolute',top:'70px',left:'17px',right:'17px',flexDirection:'column',alignItems:'stretch',padding:'18px',gap:'4px',background:'#111418',border:'1px solid #2a2f36'});});}
const dropdownCss=`.nav-dropdown{position:relative;display:flex;align-items:center;height:100%}.nav-drop-trigger{appearance:none;border:0;background:transparent;color:inherit;font:inherit;font-size:12px;font-weight:600;display:flex;align-items:center;gap:6px;padding:12px 0;cursor:pointer}.nav-drop-trigger span{font-size:14px;line-height:1;transition:transform .2s ease}.nav-dropdown-menu{position:absolute;top:calc(100% + 14px);left:50%;width:470px;transform:translate(-50%,-8px);padding:20px;background:#f4f0e8;color:#171716;border:1px solid rgba(20,20,18,.12);border-radius:16px;box-shadow:0 22px 55px rgba(0,0,0,.26);display:grid;grid-template-columns:1fr 1fr;gap:20px;opacity:0;visibility:hidden;pointer-events:none;transition:opacity .2s ease,transform .2s ease,visibility .2s ease;z-index:80}.nav-dropdown:hover .nav-dropdown-menu,.nav-dropdown:focus-within .nav-dropdown-menu,.nav-dropdown.is-open .nav-dropdown-menu{opacity:1;visibility:visible;pointer-events:auto;transform:translate(-50%,0)}.nav-dropdown:hover .nav-drop-trigger span,.nav-dropdown.is-open .nav-drop-trigger span{transform:rotate(180deg)}.nav-menu-group{display:flex;flex-direction:column;gap:2px}.nav-menu-label{font-size:9px;letter-spacing:.14em;font-weight:800;color:#8b8273;margin:0 0 8px;padding:0 8px}.nav-menu-group a{font-size:13px;color:#5c5a55;padding:8px;border-radius:8px;line-height:1.25;transition:background .18s ease,color .18s ease,transform .18s ease}.nav-menu-group a:hover{background:#e7e0d4;color:#111;transform:translateX(2px)}.nav-menu-cta{grid-column:1/-1;display:flex;align-items:center;justify-content:space-between;gap:16px;margin-top:2px;padding:14px 15px;background:#171716;color:#f4f0e8;border-radius:11px}.nav-menu-cta strong{display:block;font-size:12px;font-weight:700;margin-bottom:3px}.nav-menu-cta small{display:block;color:#aaa59b;font-size:10px}.nav-menu-cta b{font-size:18px;font-weight:400}.nav-industries-menu{width:400px;grid-template-columns:1fr 1fr}@media(max-width:1000px){.nav-dropdown{display:block;height:auto;width:100%}.nav-drop-trigger{width:100%;justify-content:space-between;padding:10px 0}.nav-dropdown-menu{position:static;width:100%;transform:none!important;display:none;opacity:1;visibility:visible;pointer-events:auto;box-shadow:none;border-radius:10px;padding:12px;margin:0 0 8px;background:#171a1d;color:#f4f0e8;grid-template-columns:1fr}.nav-dropdown.is-open .nav-dropdown-menu{display:grid}.nav-menu-label{color:#8d918f}.nav-menu-group a{color:#d7d9d6}.nav-menu-group a:hover{background:#22272b;color:#fff}.nav-menu-cta{background:#24292d}.nav-menu-cta small{color:#aeb2b0}}`;
const style=document.createElement('style');style.textContent=dropdownCss;document.head.appendChild(style);
function buildDropdown(label,groups,ctaText,ctaSub,ctaHref,extraClass=''){const wrap=document.createElement('div');wrap.className='nav-dropdown';const trigger=document.createElement('button');trigger.className='nav-drop-trigger';trigger.type='button';trigger.setAttribute('aria-expanded','false');trigger.innerHTML=`${label} <span>⌄</span>`;const panel=document.createElement('div');panel.className=`nav-dropdown-menu ${extraClass}`;groups.forEach(group=>{const g=document.createElement('div');g.className='nav-menu-group';const title=document.createElement('span');title.className='nav-menu-label';title.textContent=group.title;g.appendChild(title);group.links.forEach(item=>{const a=document.createElement('a');a.href=item[1];a.textContent=item[0];g.appendChild(a)});panel.appendChild(g)});const cta=document.createElement('a');cta.className='nav-menu-cta';cta.href=ctaHref;cta.innerHTML=`<span><strong>${ctaText}</strong><small>${ctaSub}</small></span><b>↗</b>`;panel.appendChild(cta);wrap.append(trigger,panel);return wrap;}
if(nav){const services=[...nav.children].find(a=>a.tagName==='A'&&a.textContent.trim().toLowerCase()==='services');const industries=[...nav.children].find(a=>a.tagName==='A'&&a.textContent.trim().toLowerCase()==='industries');if(services)services.replaceWith(buildDropdown('Services',[{title:'DIGITAL EXPERIENCE',links:[['Web Design & Development','web-design.html'],['Website Redesign','web-design.html#redesign'],['E-commerce','web-design.html#ecommerce']]},{title:'GROWTH & VISIBILITY',links:[['SEO & Search','seo-search.html'],['Local SEO & Business Profiles','seo-search.html#local'],['Digital Growth & CRO','digital-growth.html']]},{title:'SOFTWARE & AI',links:[['Custom Software & Platforms','software-platforms.html'],['AI & Automation','ai-automation.html'],['Mobile Products','mobile-products.html']]}],'Not sure what you need?','Tell us what you are trying to improve.','contact.html'));if(industries)industries.replaceWith(buildDropdown('Industries',[{title:'WHO WE WORK WITH',links:[['Trades & Home Services','industries.html#trades'],['Professional Services','industries.html#professional'],['Health & Beauty','industries.html#health']]},{title:'SECTORS',links:[['Hospitality & Food','industries.html#hospitality'],['Retail & E-commerce','industries.html#retail'],['Property & Automotive','industries.html#property-automotive']]}],'Explore all industries','See where we can help your business.','industries.html','nav-industries-menu'));}
document.querySelectorAll('.nav-drop-trigger').forEach(button=>button.addEventListener('click',()=>{const parent=button.closest('.nav-dropdown');const open=parent.classList.toggle('is-open');button.setAttribute('aria-expanded',String(open));document.querySelectorAll('.nav-dropdown').forEach(other=>{if(other!==parent){other.classList.remove('is-open');const t=other.querySelector('.nav-drop-trigger');if(t)t.setAttribute('aria-expanded','false')}})}));
document.addEventListener('click',e=>{if(!e.target.closest('.nav-dropdown'))document.querySelectorAll('.nav-dropdown').forEach(d=>{d.classList.remove('is-open');const t=d.querySelector('.nav-drop-trigger');if(t)t.setAttribute('aria-expanded','false')})});
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{if(innerWidth<=1000&&nav)nav.style.display='none'}));
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
(function(){const box=document.querySelector('.social-links');if(!box)return;const icons={LinkedIn:'<path d="M6.5 8.1H3.1V21h3.4V8.1ZM4.8 3A2 2 0 1 0 4.8 7 2 2 0 0 0 4.8 3ZM21 13.6c0-3.9-2.1-5.8-4.9-5.8-2.3 0-3.3 1.3-3.9 2.2V8.1H8.8V21h3.4v-6.4c0-1.7.3-3.3 2.4-3.3 2 0 2 1.9 2 3.4V21H21v-7.4Z"/>',Instagram:'<rect x="3" y="3" width="18" height="18" rx="5"></rect><circle cx="12" cy="12" r="4"></circle><circle cx="17.5" cy="6.5" r="1"></circle>',Facebook:'<path d="M14 8h3V4.5c-.5-.1-1.9-.2-3.6-.2C9.8 4.3 7.8 6.2 7.8 10v2H4.5v3.8h3.3V22h4v-6.2h3.4l.5-3.8h-3.9v-1.8c0-1.1.3-2.2 2.2-2.2Z"/>',Threads:'<path d="M17.8 11.1c-.2-3.6-2.2-5.7-5.9-5.7-3.9 0-6.2 2.2-6.2 5.3 0 3.2 2.3 5.2 5.9 5.2 2.1 0 3.7-.8 4.5-2.3.6-1.2.1-2.5-1.1-3-1.4-.6-3.3-.1-3.3 1.3 0 .8.6 1.3 1.5 1.3 1.7 0 2.6-1.5 2.6-3.8 0-3.1-1.7-4.9-4.1-4.9-2.5 0-4.1 1.5-4.1 3.9 0 2.4 1.7 3.9 4.3 3.9 1.2 0 2.2-.3 3-.9"/>',X:'<path d="M18.8 3H22l-7 8 8 10h-6.2l-4.9 6.1L6.5 21H3.3l7-8L2.6 3H9l4.5 5.6L18.8 3Zm-1.1 16.2h1.7L7 4.7H5.2l12.5 14.5Z"/>'};box.querySelectorAll('a').forEach(a=>{const label=a.getAttribute('aria-label');if(!icons[label])return;a.querySelector('.social-icon')?.remove();const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.innerHTML=icons[label];a.insertBefore(svg,a.querySelector('span:last-child'));});})();
(function(){const work=document.getElementById('workPanels');if(!work)return;const names=['property-adviser','tpm-clothing','qahwa-for-life','revamp-automotive','mooreish-delights','leia-florals','dr-mo','social-luxe','maple','nova-rituals'];work.querySelectorAll('.work-project').forEach((card,i)=>{const img=card.querySelector('.work-project-media img');if(img)img.src=`assets/work-card/${String(i+1).padStart(2,'0')}-${names[i]}.svg`;});const workCss=document.createElement('style');workCss.textContent=`@media(max-width:767px){.work-showcase{overflow:visible;padding-bottom:72px}.work-intro{padding-bottom:8px}.work-stage{height:auto;margin-top:8px}.work-stage-head{height:42px;padding-top:4px}.work-panels{position:static;display:flex;flex-direction:column;gap:16px;height:auto;padding:0 16px;overflow:visible}.work-project,.work-project.is-active{flex:0 0 auto;width:100%;height:430px;min-height:430px;border-color:#34342f;cursor:pointer;transition:none}.work-project-link{height:100%;width:100%}.work-project-media img,.work-project.is-active .work-project-media img,.work-project:not(.is-active) .work-project-media img{transform:scale(1);filter:saturate(.82) brightness(.72);transition:none}.work-project-shade,.work-project:not(.is-active) .work-project-shade{background:linear-gradient(180deg,rgba(5,5,4,.08) 0%,rgba(5,5,4,.16) 32%,rgba(5,5,4,.82) 100%)}.work-project-info{padding:22px 22px 24px}.work-project-meta{gap:5px}.work-project-meta span,.work-project:not(.is-active) .work-project-meta span{writing-mode:initial;transform:none;color:var(--gold);font-size:12px;letter-spacing:.12em}.work-project-meta small,.work-project.is-active .work-project-meta small{opacity:1;transform:none;font-size:8px;letter-spacing:.14em;color:#dedbd3}.work-project-bottom,.work-project.is-active .work-project-bottom{opacity:1;transform:none;align-items:flex-end;gap:16px}.work-project-bottom h3{font-size:34px;line-height:1.02;margin:0 0 9px}.work-project-bottom p{font-size:12px;line-height:1.5;max-width:calc(100vw - 118px);color:#d3d0c8}.work-project-arrow{width:42px;min-width:42px;height:42px;padding:0;border-radius:50%;font-size:0;gap:0}.work-project-arrow b{font-size:17px}.work-stage-foot{height:auto;display:block;padding:20px 16px 0}.work-stage-foot>span:first-child{display:none}.work-stage-hint{font-size:9px;color:#77746d}}@media(max-width:430px){.work-panels{padding:0 14px;gap:14px}.work-project,.work-project.is-active{height:390px;min-height:390px}.work-project-info{padding:19px 19px 21px}.work-project-bottom h3{font-size:30px}.work-project-bottom p{font-size:11px;max-width:calc(100vw - 100px)}}`;document.head.appendChild(workCss);})();
(function(){const grid=document.querySelector('.industry-grid');if(!grid)return;const cards=[...grid.querySelectorAll('a')];const property=cards.find(a=>a.querySelector('strong')?.textContent.trim()==='Property');if(property){const title=property.querySelector('strong');const detail=property.querySelector('small');if(title)title.textContent='Property & Automotive';if(detail)detail.textContent='Estate Agents · Developers · Property Services · Automotive';property.setAttribute('href','#contact');}})();
(function(){const pricing=[...document.querySelectorAll('.primary-nav a')].find(a=>a.textContent.trim().toLowerCase()==='pricing');if(pricing)pricing.href='pricing.html';})();
(function(){const headerCss=`
.site-header .nav{height:90px;gap:32px}
.site-header .brand{gap:14px}
.site-header .brand-mark{width:60px;height:60px;flex-basis:60px}
.site-header .brand-mark img{width:60px;height:60px}
.site-header .brand-copy strong{font-size:20px;letter-spacing:.035em;white-space:nowrap}
.site-header .brand-copy small{font-size:8px;letter-spacing:.17em;margin-top:6px;white-space:nowrap}
.site-header .primary-nav{gap:27px;font-size:13px;align-items:center}
.site-header .nav-drop-trigger{font-size:13px;font-weight:500}
.site-header .nav-drop-trigger span{font-size:13px}
.site-header .nav>.button{min-height:52px;padding:0 23px;font-size:12px;letter-spacing:.02em;white-space:nowrap}
@media(max-width:1100px){.site-header .nav{gap:18px}.site-header .primary-nav{gap:16px;font-size:12px}.site-header .nav>.button{padding:0 17px}.site-header .brand-copy strong{font-size:18px}.site-header .brand-mark,.site-header .brand-mark img{width:56px;height:56px}.site-header .brand-mark{flex-basis:56px}}
@media(max-width:760px){.site-header .nav{height:72px}.site-header .brand{gap:10px}.site-header .brand-mark,.site-header .brand-mark img{width:50px;height:50px}.site-header .brand-mark{flex-basis:50px}.site-header .brand-copy strong{font-size:16px}.site-header .brand-copy small{font-size:6.5px;letter-spacing:.14em;margin-top:5px}.site-header .menu-toggle{font-size:22px}.site-header .primary-nav{top:72px}}
`;
const headerStyle=document.createElement('style');headerStyle.id='tpm-master-header';headerStyle.textContent=headerCss;document.head.appendChild(headerStyle);})();
(function(){const footerCss=`
.footer-connect{padding:82px 0 0;text-align:center}
.footer-connect-heading{display:flex;align-items:center;justify-content:center;gap:24px;margin-bottom:30px}
.footer-connect-heading span{width:88px;height:1px;background:#2c2c28}
.footer-connect-heading h2{margin:0;font-size:10px;letter-spacing:.28em;color:var(--gold);font-weight:700}
.social-links{display:flex;justify-content:center;align-items:center;gap:28px;flex-wrap:wrap}
.social-links a{display:inline-flex!important;align-items:center;gap:8px;border:0!important;padding:0!important;background:transparent!important;border-radius:0!important;color:#99968e;font-size:10px;letter-spacing:.04em;transition:color .2s ease!important;transform:none!important}
.social-links a:hover{color:#f4f1e9;transform:none!important}
.social-links a svg{width:20px!important;height:20px!important;display:block;flex:0 0 20px;fill:currentColor;stroke:currentColor;stroke-width:0;overflow:visible}
.social-links a:nth-child(2) svg{fill:none;stroke:currentColor;stroke-width:1.7}
.social-links a:nth-child(4) svg{fill:none;stroke:currentColor;stroke-width:1.25;stroke-linecap:round;stroke-linejoin:round}
.footer-divider{display:none!important}
.footer-brand-center{padding-top:72px;text-align:center;display:flex;flex-direction:column;align-items:center}
.footer-brand-link{display:inline-flex!important;margin:0 auto!important}
.footer-brand-center>p{margin:22px 0 0;color:#6f6c64;font-size:11px}
.footer-locations{display:flex;justify-content:center;gap:22px;margin-top:18px;color:#77746d;font-size:9px;letter-spacing:.12em}
.footer-bottom{margin-top:58px;padding-top:22px;padding-bottom:24px;border-top:1px solid #22221f}
@media(max-width:600px){.footer-connect{padding-top:64px}.footer-connect-heading{gap:14px;margin-bottom:24px}.footer-connect-heading span{width:46px}.social-links{gap:18px 22px}.social-links a{font-size:9px}.social-links a svg{width:18px!important;height:18px!important;flex-basis:18px}.footer-brand-center{padding-top:56px}.footer-brand-center>p{font-size:10px;padding:0 20px}.footer-locations{gap:14px}.footer-bottom{margin-top:44px}}
`;
const footerStyle=document.createElement('style');footerStyle.id='tpm-clean-footer';footerStyle.textContent=footerCss;document.head.appendChild(footerStyle);})();